name: Deploy Bot Cloud Function
concurrency: bot-concurrency-group

on:
  push:
    branches: [ main ]

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.gcp_credentials }}

    - id: deploy
      uses: google-github-actions/deploy-cloud-functions@v0
      with:
        name: Bot
        runtime: go116

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: Bot-v${{ steps.deploy.outputs.version }}
