name: Test Terraform Format

on:
  pull_request:

jobs:
  test:
    name: Test Terraform Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.2.6'
      - run: terraform fmt -recursive -check
